services:
  api:
    image: jglchen/laravel-auth-jwt
    command: "php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - auth-jwt-sqlite:/app/database

  next:
    image: jglchen/user-next-jwt
    ports:
      - 3000:3000

volumes:
  auth-jwt-sqlite: